language: node_js
node_js:
  - 12
before_script:
  - npm install
  - npm run build

deploy:
  - provider: npm
    skip_cleanup: true
    api_token: $NPM_API_KEY
    email: "arielhernandezmusa@gmail.com"
    on:
      tags: true
